DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  key TEXT UNIQUE NOT NULL,
  score INTEGER DEFAULT 0,
  day TEXT
);

CREATE TABLE game (
  key TEXT PRIMARY KEY,
  token TEXT UNIQUE NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  char TEXT,
  FOREIGN KEY (key) REFERENCES user (key)
);
